### ISSUE TITLE
Unsupported SSL protocol version error

### ISSUE THREAD

**Issue by speller** [paypal/merchant-sdk-php#107]
### Required Information

- PHP Version: 5.6.16 with following relevant configs:
Registered Stream Socket Transports: tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
cURL Information: 7.44.0
SSL Version: OpenSSL/1.0.1t

- SDK Version: 3.9.1

### Issue Description
Receive the error "Unsupported SSL protocol version" when running under live configuration. The issue is in CURL config. It work fine if I hardcode the CURL_SSLVERSION value to 4. With 5 or 6 it cause error.

The problem is I can not set the config value without hardcoding the package insights. It is no way to set  it up.

**Comment by ppmtscory** [comment]
We'll have somebody take a look and get back to you here.

**Comment by jaypatel512** [comment]
Hey @speller !

I wanted to confirm with you that the openssl version you have mentioned is the one you see in your curl, and not by running `openssl version` on a command line. PHP curl library has its own set of openssl library which is different from openssl.so module that you package along with php. 

To find out the proper details of what version of openssl your curl is using, you may want to print `
print_r(curl_version());` in your browser, and verify that. 

Based on the [CURLOPT_SSLVERSION](https://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html), you may be able to use either `CURL_SSLVERSION_TLSv1(1)` or `CURL_SSLVERSION_TLSv1_2 (6)`.

Currently, based on [TLS updates](https://github.com/paypal/TLS-update), sandbox environment currently has a TLSv1.2 only setup, however, live environment is scheduled for next year. We wish to make sure that you use the proper setup now, so that when the live environment is restricted to TLSv1.2 only, you will not face any issues. That is why it is very important to verify that the code you write on live should also work on sandbox. 

I am easily able to work with sandbox and live using following details:

```
# CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1(1), or CURL_SSLVERSION_TLSv1_2(6)
> echo json_encode(curl_version());
{
	"version_number": 471297,
	"age": 3,
	"features": 573981,
	"ssl_version_number": 0,
	"version": "7.49.1",
	"host": "x86_64-apple-darwin15.5.0",
	"ssl_version": "OpenSSL\/1.0.2h",
	"libz_version": "1.2.5",
	"protocols": ["dict", "file", "ftp", "ftps", "gopher", "http", "https", "imap", "imaps", "ldap", "ldaps", "pop3", "pop3s", "rtsp", "smb", "smbs", "smtp", "smtps", "telnet", "tftp"]
}
```

**Comment by jaypatel512** [comment]
Closing this issue. For any TLS issues, please refer to https://github.com/paypal/TLS-update repository. We are adding more and more details for each language.
