### ISSUE TITLE
Warning: Ambiguous class resolution in Composer

### ISSUE THREAD

**Issue by minutiae** [paypal/merchant-sdk-php#74]
When installing by composer ( have updated to the latest composer ), I receive dozens of the following Warnings:

Warning: Ambiguous class resolution, "PayPalAPIInterfaceServiceService" was found in both "/var/www/site.dev/vendor/paypal/merchant-sdk-php/lib/PayPalAPIInterfaceService/PayPalAPIInterfaceServiceService.php" and "/var/www/site.dev/vendor/paypal/merchant-sdk-php/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceServiceService.php", the first will be used.

**Comment by osoria** [comment]
+1

**Comment by david-fanin** [comment]
I have the same issue.

**Comment by cschramm80** [comment]
Same here. Has anyone a solution on this?

**Comment by nsanden** [comment]
+1

**Comment by felixdv** [comment]
Same here, using "paypal/merchant-sdk-php":"2.11.118".

**Comment by rtconner** [comment]
```
$ composer install --optimize-autoloader
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
Warning: Ambiguous class resolution, "IlluminateQueueClosure" was found in both "/var/www/site/vendor/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php" and "/var/www/site/vendor/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php", the first will be used.`
```

**Comment by shakaran** [comment]
I came from Google, from this post https://blog.liplex.de/getting-rid-of-ambiguous-class-resolution-warnings/ that help me a lot for avoid this annoning warnings.

As the blog autor says this is produced because the example classes are includes in the distribution package. That should be referenced to original classes and avoid duplication.

There are a dirty workaround that the blog mention changing in composer.json:

	"scripts": {
		"pre-autoload-dump": [
			"rm -rf vendor/paypal/merchant-sdk-php/lib/services"
		]
	},

So you will remove the warnings removing the example files. Please Paypal assign more priority to this, it is a easy warning to solve and avoid headaches and warnings flood to developers using composer.

**Comment by klunejko** [comment]
still happening, installed using "paypal/merchant-sdk-php":"~2.5",

**Comment by jaypatel512** [comment]
This issue should have been resolved now. We encourage you to use the latest release.
